apiVersion: v1
kind: Secret
metadata:
  name: vault-configuration
  namespace: argocd
  annotations:
    avp.kubernetes.io/path: "home-k8s/argocd-vault-plugin"
type: Opaque
data:
  AVP_TYPE: vault
  AVP_AUTH_TYPE: token
  VAULT_ADDR: <vault-address>
  VAULT_TOKEN: <vault-token>
