{
 "title": "Prometheus Speedtest Exporter",
 "description": "Dashboard for https://github.com/nlamirault/speedtest_exporter",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Ping (ms)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "speedtest_ping_latency_milliseconds"
    }
   ]
  },
  {
   "title": "Ping (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(speedtest_ping_latency_milliseconds) by (instance)"
    }
   ]
  },
  {
   "title": "Download (bps)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(speedtest_download_bits_per_second) by (instance)"
    }
   ]
  },
  {
   "title": "Download (bps)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(speedtest_download_bits_per_second) by (instance)"
    }
   ]
  },
  {
   "title": "Upload (bps)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(speedtest_upload_bits_per_second) by (instance)"
    }
   ]
  },
  {
   "title": "Upload (bps)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(speedtest_upload_bits_per_second) by (instance)"
    }
   ]
  }
 ]
}